export VERSION="1.2.0"
export BUILD=1
export PREFIX=""
export DESC="DroidSpace Kernel for Poco F3"
export DEVICE="alioth"
export TYPE="release"
export LEVEL=1
export EXTRA=""
export SHAB=""
export SHAK=""
